version: '3.8'

services:
  # Main application
  stock-manager:
    build: .
    container_name: stock-manager-app
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config:ro
    environment:
      - ENVIRONMENT=simulation
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - redis
    networks:
      - stock-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: stock-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stock_manager
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stock_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - stock-network

  # Redis for caching and real-time data
  redis:
    image: redis:7-alpine
    container_name: stock-manager-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - stock-network

volumes:
  postgres_data:
  redis_data:

networks:
  stock-network:
    driver: bridge 